---
locale: es
tags:
- booleanos
- expresiones
- and
- operadores-booleanos
layout: input_bottom
editor: code
type: problem
extra_visible: true
teacher_info: ''
manual_evaluation: false
choices: []
name: El retorno del booleano
